server:
  port: 8080

spring:
  profiles:
    active: mysql
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: cn.edu.usc.quzhijie.emrservice
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: EUqxSvI4extlwRUeCDNBVq4p6SIp1JSyK7hTXAbvE7M=
  expiration: 900000
  refresh-token-expiration: 604800000
