server:
  port: 8080

spring:
  profiles:
    active: mysql
  application:
    name: user-service

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.usc.quzhijie.emrservice.user.entity, cn.edu.usc.quzhijie.emrservice.user.vo
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: EUqxSvI4extlwRUeCDNBVq4p6SIp1JSyK7hTXAbvE7M=
  expiration: 3600000
