server:
  port: 8080

spring:
  profiles:
    active: mysql-test
  application:
    name: emr-service
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: cn.edu.usc.quzhijie.emrservice
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: EUqxSvI4extlwRUeCDNBVq4p6SIp1JSyK7hTXAbvE7M=
  expiration: 900000
  refresh-token-expiration: 604800000

file:
  base-dir: C:/Users/LuckyBY/Desktop/EMR-ARIMA/EMR-ARIMA-service/emr-files
  access-url: http://localhost:8080/files
