spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/emr_arima_test?useSSL=false&serverTimezone=UTC
    username: emr_test
    password: LuckyBY.#dev*0128